/*
 * This file was automatically generated by EvoSuite
 * Sun Apr 08 21:42:10 GMT 2018
 */

package java_programs;

import org.junit.Test;
import static org.junit.Assert.*;
import java.util.ArrayList;
import java_programs.NEXT_PERMUTATION;

public class NEXT_PERMUTATION_ESTest {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      NEXT_PERMUTATION nEXT_PERMUTATION0 = new NEXT_PERMUTATION();
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ArrayList<Integer> arrayList0 = new ArrayList<Integer>();
      // Undeclared exception!
      try { 
        NEXT_PERMUTATION.next_permutation(arrayList0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // -2
         //
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      ArrayList<Integer> arrayList0 = new ArrayList<Integer>();
      Integer integer0 = Integer.valueOf((-884));
      arrayList0.add(integer0);
      arrayList0.add(integer0);
      ArrayList<Integer> arrayList1 = NEXT_PERMUTATION.next_permutation(arrayList0);
      assertEquals(0, arrayList1.size());
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      ArrayList<Integer> arrayList0 = new ArrayList<Integer>();
      Integer integer0 = Integer.valueOf((-884));
      arrayList0.add(integer0);
      Integer integer1 = new Integer(1731);
      arrayList0.add(integer1);
      ArrayList<Integer> arrayList1 = NEXT_PERMUTATION.next_permutation(arrayList0);
      Integer integer2 = new Integer(887);
      arrayList1.add(integer1);
      arrayList1.add(integer2);
      ArrayList<Integer> arrayList2 = NEXT_PERMUTATION.next_permutation(arrayList1);
      NEXT_PERMUTATION.next_permutation(arrayList1);
      NEXT_PERMUTATION.next_permutation(arrayList0);
      assertEquals(4, arrayList0.size());
      assertSame(arrayList0, arrayList2);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      ArrayList<Integer> arrayList0 = new ArrayList<Integer>();
      Integer integer0 = Integer.valueOf((-884));
      arrayList0.add(integer0);
      arrayList0.add(integer0);
      Integer integer1 = new Integer(1731);
      arrayList0.add(integer1);
      ArrayList<Integer> arrayList1 = NEXT_PERMUTATION.next_permutation(arrayList0);
      NEXT_PERMUTATION.next_permutation(arrayList0);
      assertEquals(3, arrayList0.size());
      assertSame(arrayList0, arrayList1);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      // Undeclared exception!
      try { 
        NEXT_PERMUTATION.next_permutation((ArrayList<Integer>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }
}
